/* =========================================================
   LUNA NEGRA · Jessica — El Oráculo
   Dataset completo de 78 cartas del Tarot Rider-Waite.
   ========================================================= */

/* Cada carta:
   {
     id, num, suit, name, glyph, glyph2,
     keywords: [..],
     upright: { general, amor, dinero, salud, prosperidad },
     reversed: { general, amor, dinero, salud, prosperidad }
   }

   - suit: 'major' para los 22 Arcanos Mayores.
           'wands' | 'cups' | 'swords' | 'pentacles' para los menores.
   - En los Arcanos Menores, los "court cards" se identifican con rank: 'page' | 'knight' | 'queen' | 'king'.
*/

const DECK = [
  // ========== 22 ARCANA MAYOR ==========
  {
    id: 'major-0', num: 0, suit: 'major', rank: 'fool',
    name: 'El Loco', glyph: '🃏',
    keywords: ['comienzo', 'libertad', 'inocencia', 'salto de fe'],
    upright: {
      general: 'Un nuevo ciclo se abre. Saltá sin mirar, porque la red aparecerá.',
      amor: 'Alguien nuevo llega sin aviso. Dejá que el corazón tome la iniciativa antes que la cabeza.',
      dinero: 'Oportunidad inesperada, pero sin plan. Invertí en vos antes de apostar afuera.',
      salud: 'Energía renovada, vitalidad alta. Cuidado con los excesos por no saber parar.',
      prosperidad: 'El universo te está diciendo: empezá. La abundancia sigue a quien empieza.',
    },
    reversed: {
      general: 'Estás por lanzarte sin paracaídas. Frená, mirá el mapa una vez más.',
      amor: 'Apego que te frena, o huida que te cuesta entender. Date tiempo.',
      dinero: 'Gasto impulsivo a la vista. La libertad no es gastar sin ton ni son.',
      salud: 'Cansancio mental por no escuchar al cuerpo. Frená.',
      prosperidad: 'Sembrás en demasiados frentes. Concentrá.',
    },
  },
  {
    id: 'major-1', num: 1, suit: 'major',
    name: 'El Mago', glyph: '🜲',
    keywords: ['voluntad', 'creación', 'habilidad', 'manifestar'],
    upright: {
      general: 'Tenés todas las herramientas. Ahora: usalas.',
      amor: 'Podés atraer exactamente lo que querés si te animás a declarar tu intención.',
      dinero: 'Momento ideal para emprender, negociar, lanzar una idea.',
      salud: 'Tu mente es tu mejor medicina. Visualizar cura.',
      prosperidad: 'El universo obedece a quien actúa con propósito.',
    },
    reversed: {
      general: 'Tienes el poder pero lo estás regalando. Recuperá el centro.',
      amor: 'Estás manipulando o te están manipulando. Volvé al corazón.',
      dinero: 'Talentos desaprovechados. Falta decisión, no capacidad.',
      salud: 'La cabeza está saboteando al cuerpo. Bajá el ritmo mental.',
      prosperidad: 'Riqueza mal encauzada. Asegurate de que tu poder sirva a algo.',
    },
  },
  {
    id: 'major-2', num: 2, suit: 'major',
    name: 'La Sacerdotisa', glyph: '☾',
    keywords: ['intuición', 'misterio', 'inconsciente', 'sabiduría interior'],
    upright: {
      general: 'Lo que no se dice está hablando más fuerte. Escuchá tu intuición.',
      amor: 'Sentimientos silenciados. Hay algo que no se animan a poner en palabras.',
      dinero: 'No conviene apurar decisiones financieras. Esperá a ver claro.',
      salud: 'Prestá atención a las señales suaves del cuerpo.',
      prosperidad: 'La abundancia que llega por detrás, no por delante.',
    },
    reversed: {
      general: 'Estás ignorando tu propia voz. Se está acumulando marea adentro.',
      amor: 'Secretos que pesan en la relación. Sacalo.',
      dinero: 'Información que te ocultan. Pedí los papeles.',
      salud: 'Represión emocional que se está haciendo carne.',
      prosperidad: 'Riqueza escondida en vos que no estás mirando.',
    },
  },
  {
    id: 'major-3', num: 3, suit: 'major',
    name: 'La Emperatriz', glyph: '♀',
    keywords: ['fertilidad', 'abundancia', 'cuerpo', 'naturaleza'],
    upright: {
      general: 'Algo que plantaste está floreciendo.',
      amor: 'Amor pleno, conexión profunda. Potencial de embarazo o nuevo ciclo.',
      dinero: 'Ingresos que crecen. Comprá, invertí en algo tangible.',
      salud: 'Cuerpo fuerte. Buena alimentación, sensualidad sana.',
      prosperidad: 'La abundancia es tu estado natural.',
    },
    reversed: {
      general: 'Descuido de lo básico: casa, cuerpo, comida.',
      amor: 'Dependencia emocional o territorialidad. Soltá el control.',
      dinero: 'Inflación personal: gastás más de lo que entra.',
      salud: 'Cambios hormonales, fatiga. Mimos al cuerpo ya.',
      prosperidad: 'No podés cosechar lo que nunca sembraste.',
    },
  },
  {
    id: 'major-4', num: 4, suit: 'major',
    name: 'El Emperador', glyph: '♂',
    keywords: ['estructura', 'autoridad', 'orden', 'límites'],
    upright: {
      general: 'Estructura firme. Tomá el mando.',
      amor: 'Alguien mayor o más consolidado ofrece estabilidad.',
      dinero: 'Momento de apretar la administración. Vence quien ordena primero.',
      salud: 'Disciplina y rutina. Resultados sólidos.',
      prosperidad: 'Edificás fortuna ladrillo por ladrillo.',
    },
    reversed: {
      general: 'Autoritarismo o ausencia total de orden. ¿Cuál de los dos?',
      amor: 'Relación demasiado rígida o demasiado ausente. Hablar y pactar.',
      dinero: 'Mal manejo de alguien que debería cuidarte.',
      salud: 'Cuerpo rígido, contracturas, stresses.',
      prosperidad: 'Imperio sin cimientos. Volvé al ladrillo.',
    },
  },
  {
    id: 'major-5', num: 5, suit: 'major',
    name: 'El Sumo Sacerdote', glyph: '✝',
    keywords: ['tradición', 'enseñanza', 'creencia', 'guía espiritual'],
    upright: {
      general: 'Hay un saber antiguo intentando llegar. Dejalo entrar.',
      amor: 'Relación con raíces convencionales. Boda, compromiso, promesas.',
      dinero: 'Inversión segura, conservadora, a largo plazo.',
      salud: 'Sanación por lo probado: médico, dieta, práctica.',
      prosperidad: 'La fortuna construida con constancia.',
    },
    reversed: {
      general: 'Creyente ciego o ciego a lo sagrado. Cuestioná.',
      amor: 'Relación que intenta encajar en un molde que no le cabe.',
      dinero: 'Consejo financiero dudoso. No firmes lo que no entendés.',
      salud: 'Terapia alternativa no probada. Cuidado.',
      prosperidad: 'Riqueza atada a mandatos viejos.',
    },
  },
  {
    id: 'major-6', num: 6, suit: 'major',
    name: 'Los Enamorados', glyph: '♡',
    keywords: ['unión', 'elección', 'deseo', 'par'],
    upright: {
      general: 'Decisión del corazón. Elegí con todo.',
      amor: 'Alianza, encuentro, declaración.',
      dinero: 'Opciones claras. Toca decidir y comprometerte.',
      salud: 'Sistema hormonal y corazón en armonía.',
      prosperidad: 'Crecimiento en pareja de socios.',
    },
    reversed: {
      general: 'Elegís entre lo que querés y lo que conviene. Mal.',
      amor: 'Desamor, triángulo, indecisión.',
      dinero: 'Alianza comercial a punto de romperse.',
      salud: 'Bloqueo emocional que enferma.',
      prosperidad: 'Socios que se atraen para mal.',
    },
  },
  {
    id: 'major-7', num: 7, suit: 'major',
    name: 'El Carro', glyph: '☌',
    keywords: ['avance', 'voluntad', 'dirección', 'victoria'],
    upright: {
      general: 'Avanzá. El mundo está esperando que decidas hacia dónde.',
      amor: 'Relación que crece rápido. Decidirse en movimiento.',
      dinero: 'Buen momento para escalar, expandir, invertir fuerte.',
      salud: 'Recuperación rápida con disciplina.',
      prosperidad: 'Imparable si mantenés el rumbo.',
    },
    reversed: {
      general: 'Avanzás pero sin saber a dónde. Frená y orientate.',
      amor: 'Relación que no sabe a dónde va.',
      dinero: 'Crecimiento fuera de control.',
      salud: 'Accidente por sobreexigencia.',
      prosperidad: 'Velocidad sin dirección.',
    },
  },
  {
    id: 'major-8', num: 8, suit: 'major',
    name: 'La Fuerza', glyph: '🦁',
    keywords: ['coraje', 'entereza', 'paciencia', 'doma'],
    upright: {
      general: 'Poder sereno. No necesitás gritar.',
      amor: 'Amor profundo que doma sin someter.',
      dinero: 'Inversión que se gana con paciencia.',
      salud: 'Sanación que requiere voluntad.',
      prosperidad: 'La constancia extrema se vuelve fortuna.',
    },
    reversed: {
      general: 'Fuerza bruta, agotamiento, ira contenida.',
      amor: 'Celos, control, sumisión.',
      dinero: 'Apuestas por agotamiento mental.',
      salud: 'Burn-out temprano.',
      prosperidad: 'Empujás sin parar pero no construís.',
    },
  },
  {
    id: 'major-9', num: 9, suit: 'major',
    name: 'El Ermitaño', glyph: '🕯',
    keywords: ['soledad', 'sabiduría', 'interior', 'búsqueda'],
    upright: {
      general: 'Necesitás silencio para escuchar tu propia voz.',
      amor: 'Tiempo a solas antes de la próxima pareja.',
      dinero: 'Estudio, estrategia, lectura antes de gastar.',
      salud: 'Mindfulness, ayuno, retiro digital.',
      prosperidad: 'La fortuna se construye en silencio.',
    },
    reversed: {
      general: 'Aislamiento que enferma. Salí un poco.',
      amor: 'Huido del mundo para no amar.',
      dinero: 'Avaricia disfrazada de prudencia.',
      salud: 'Depresión silenciosa.',
      prosperidad: 'Cerrado en tu burbuja de esfuerzo.',
    },
  },
  {
    id: 'major-10', num: 10, suit: 'major',
    name: 'La Rueda de la Fortuna', glyph: '🎡',
    keywords: ['ciclo', 'destino', 'cambio', 'suerte'],
    upright: {
      general: 'Lo que sube, baja. Lo que baja, sube. Aprovechá la cresta.',
      amor: 'Encuentro kármico. Persona que vuelve o llega para enseñarte.',
      dinero: 'Suerte financiera fuerte. Apuesta con tu instinto.',
      salud: 'Mejora cíclica. El cuerpo responde.',
      prosperidad: 'Subida en el ciclo. Capitalizá.',
    },
    reversed: {
      general: 'Resistís el cambio. Apretás la rueda y gira más fuerte.',
      amor: 'Patrón tóxico que vuelve.',
      dinero: 'Mala racha. Aguanta sin hacer locuras.',
      salud: 'Crisis cíclica. Pasa.',
      prosperidad: 'Fortuna en bajada. Cubre gastos básicos.',
    },
  },
  {
    id: 'major-11', num: 11, suit: 'major',
    name: 'La Justicia', glyph: '⚖',
    keywords: ['equilibrio', 'verdad', 'causa-efecto', 'corte'],
    upright: {
      general: 'Recibís lo que diste. La balanza es exacta.',
      amor: 'Relación basada en equidad. Comunicar lo justo.',
      dinero: 'Buen momento para contratos, legal, firmar.',
      salud: 'Equilibrio hormonal, dieta pareja.',
      prosperidad: 'Lo cosechado de antes. Justa distribución.',
    },
    reversed: {
      general: 'Algo se rompió. Hay que pagar o pedir.',
      amor: 'Desafecto que no se atiende.',
      dinero: 'Asunto legal a resolver.',
      salud: 'Desbalance hormonal.',
      prosperidad: 'Plata mal repartida: tuya o ajena.',
    },
  },
  {
    id: 'major-12', num: 12, suit: 'major',
    name: 'El Colgado', glyph: '🝎',
    keywords: ['sacrificio', 'nueva mirada', 'pausa', 'entrega'],
    upright: {
      general: 'Pará. La respuesta llega invertida, literal: de cabeza.',
      amor: 'Soltar para recibir. Renunciá al control.',
      dinero: 'Inversión con horizonte largo. Paciencia.',
      salud: 'Curarse en otra posición literal del cuerpo.',
      prosperidad: 'La fortuna llega cuando dejás de insistir.',
    },
    reversed: {
      general: 'Estás sacrificando lo que no te corresponde.',
      amor: 'Relación que solo da para uno.',
      dinero: 'Deudas kármicas. Pagalas.',
      salud: 'Retención, defensas emocionales.',
      prosperidad: 'Esperar sin actuar se vuelve excusa.',
    },
  },
  {
    id: 'major-13', num: 13, suit: 'major',
    name: 'La Muerte', glyph: '☠',
    keywords: ['fin', 'transformación', 'cierre', 'renacer'],
    upright: {
      general: 'Algo muere. Y te conviene que muera.',
      amor: 'Final de etapa. Hay duelo, sí. Pero hay aire nuevo.',
      dinero: 'Cierre de un ciclo económico viejo.',
      salud: 'Sanación profunda. Cuerpo elimina lo viejo.',
      prosperidad: 'Herencia que entra. Cierre y comienzo.',
    },
    reversed: {
      general: 'Te aferrás a lo muerto. Soltá el puente.',
      amor: 'No querés soltar a alguien o algo que ya se fue.',
      dinero: 'Deudas viejas. Reestructurar.',
      salud: 'Resistencia a curarse. Hacelo.',
      prosperidad: 'Esperando la herencia sin actuar.',
    },
  },
  {
    id: 'major-14', num: 14, suit: 'major',
    name: 'La Templanza', glyph: '🕊',
    keywords: ['equilibrio', 'alquimia', 'paciencia', 'mezcla'],
    upright: {
      general: 'Mezclá lo bueno con lo bueno. Alquimia diaria.',
      amor: 'Pareja que se conoce con tiempo. Ritmo lento.',
      dinero: 'Inversión diversificada. Equilibrio en presupuesto.',
      salud: 'Dieta, equilibrio hormonal, hábitos.',
      prosperidad: 'La fortuna del que mezcla sabiamente.',
    },
    reversed: {
      general: 'Excesos por todos lados. Volvé al centro.',
      amor: 'Relación desigual, ni frío ni caliente.',
      dinero: 'Más para uno que para otro.',
      salud: 'Inflamación, retención. Dieta ya.',
      prosperidad: 'Fortuna desigual. Reorganizar.',
    },
  },
  {
    id: 'major-15', num: 15, suit: 'major',
    name: 'El Diablo', glyph: '😈',
    keywords: ['atadura', 'pasión', 'sombra', 'apego'],
    upright: {
      general: 'Hay un pacto. ¿Es con vos o con tu sombra?',
      amor: 'Adicción a alguien, sexo compulsivo, vínculos kármicos.',
      dinero: 'Endeudamiento tóxico. Placeres caros.',
      salud: 'Vicios dañinos: tabaco, alcohol, azúcar.',
      prosperidad: 'Riqueza que te atrapa.',
    },
    reversed: {
      general: 'Despertás de un pacto que no era tuyo.',
      amor: 'Soltás a alguien con quien estabas atado.',
      dinero: 'Liberación de deuda.',
      salud: 'Soltás un vicio. Afuera.',
      prosperidad: 'Patrimonio que se libera.',
    },
  },
  {
    id: 'major-16', num: 16, suit: 'major',
    name: 'La Torre', glyph: '🗼',
    keywords: ['quiebre', 'revelación', 'trueno', 'derrumbe'],
    upright: {
      general: 'Cae lo que estaba mal construido. Mejor.',
      amor: 'Ruptura reveladora. O revelación que rompe.',
      dinero: 'Crack financiero. Oportunidad a la larga.',
      salud: 'Crisis. Después, sanación.',
      prosperidad: 'Caída de estructuras viejas. Aceptalo.',
    },
    reversed: {
      general: 'Caída que se retrasa. No te salva, te adivierte.',
      amor: 'Crisis pareja, evitada por ahora.',
      dinero: 'Crack que se está gestando.',
      salud: 'Síntomas que no atienden.',
      prosperidad: 'Burbuja a punto de estallar.',
    },
  },
  {
    id: 'major-17', num: 17, suit: 'major',
    name: 'La Estrella', glyph: '✦',
    keywords: ['esperanza', 'guía', 'serenidad', 'fe'],
    upright: {
      general: 'Después de la tormenta, claridad. Confía.',
      amor: 'Alguien luminoso aparece o estás sanando.',
      dinero: 'Flujo dulce. No te apures.',
      salud: 'Cuerpo en serenidad. Bien.',
      prosperidad: 'Fortuna guiada por algo más grande.',
    },
    reversed: {
      general: 'Fe rota. Volvé a creer poco a poco.',
      amor: 'Desilusión que pasaste queriendo pasar.',
      dinero: 'Espejismos financieros. Volvé a los datos.',
      salud: 'Resaca emocional. Reposá.',
      prosperidad: 'Esperanza sin acción. Aterrizá.',
    },
  },
  {
    id: 'major-18', num: 18, suit: 'major',
    name: 'La Luna', glyph: '🌙',
    keywords: ['ilusión', 'sueño', 'inconsciente', 'engaño'],
    upright: {
      general: 'No todo es lo que parece. Esperá aclare.',
      amor: 'Alguien no te dice todo. Investigá.',
      dinero: 'Operación opaca. Leé la letra chica.',
      salud: 'Síntomas que parecen una cosa y son otra. Andá al médico.',
      prosperidad: 'Plata que entra y no sabés de dónde.',
    },
    reversed: {
      general: 'La niebla se levanta. Empezás a ver.',
      amor: 'Mentira que sale a la luz.',
      dinero: 'Fraude detectado o por cerrar.',
      salud: 'Diagnóstico claro llega.',
      prosperidad: 'Recuperás algo creías perdido.',
    },
  },
  {
    id: 'major-19', num: 19, suit: 'major',
    name: 'El Sol', glyph: '☀',
    keywords: ['alegría', 'éxito', 'claridad', 'plenitud'],
    upright: {
      general: 'Día claro. Sí. Sí. Sí.',
      amor: 'Amor pleno, visible, luminoso.',
      dinero: 'Auge financiero real.',
      salud: 'Vigor total.',
      prosperidad: 'La luz entra a tu casa. Y a tu cuenta.',
    },
    reversed: {
      general: 'Nubes que se están yendo. Aguanta unas horas más.',
      amor: 'Alegría que tarda. Paciencia.',
      dinero: 'Optimismo desmedido. Asegurate.',
      salud: 'Resaca de exceso.',
      prosperidad: 'Éxito con doble filo.',
    },
  },
  {
    id: 'major-20', num: 20, suit: 'major',
    name: 'El Juicio', glyph: '📯',
    keywords: ['llamado', 'despertar', 'renacer', 'verdad'],
    upright: {
      general: 'Llamado profundo. Es momento de responder.',
      amor: 'Reconexión con alguien. O con vos mismo/a.',
      dinero: 'Segunda oportunidad financiera.',
      salud: 'Renacer corporal. Tratamiento grande funciona.',
      prosperidad: 'Bendiciones que llegan por juicio propio.',
    },
    reversed: {
      general: 'No estás escuchando. La voz sigue sonando.',
      amor: 'Perdón postergado. Hacelo.',
      dinero: 'Decisión financiera postergada.',
      salud: 'Diagnóstico ignorado.',
      prosperidad: 'Oportunidad pasada. Próxima.',
    },
  },
  {
    id: 'major-21', num: 21, suit: 'major',
    name: 'El Mundo', glyph: '🌍',
    keywords: ['cierre', 'logro', 'plenitud', 'integración'],
    upright: {
      general: 'Ciclo cumplido. Celebrá. Y empezá otro.',
      amor: 'Amor total, integrado, eterno (o casi).',
      dinero: 'Cierre exitoso de proyecto.',
      salud: 'Cuerpo integrado. Bien.',
      prosperidad: 'Abundancia plena, merecida.',
    },
    reversed: {
      general: 'Falta algo para cerrar. Buscá qué.',
      amor: 'Cierre pendiente en historia.',
      dinero: 'Trámite sin cerrar.',
      salud: 'Cuerpo pide cerrar un ciclo.',
      prosperidad: 'Falta integración para gozar lo ganado.',
    },
  },

  // ========== 14 BASTOS (fuego) ==========
  // Ace
  ...generateSuit('wands', 'Bastos', '🔥'),
  // ========== 14 COPAS (agua) ==========
  ...generateSuit('cups', 'Copas', '💧'),
  // ========== 14 ESPADAS (aire) ==========
  ...generateSuit('swords', 'Espadas', '🌬'),
  // ========== 14 OROS (tierra) ==========
  ...generateSuit('pentacles', 'Oros', '🌍'),
];

/* ===== Helper: construye los 14 naipes de un palo ===== */
function generateSuit(suit, name, glyph) {
  const pips = ['As', 'Dos', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'Siete', 'Ocho', 'Nueve', 'Diez', 'Sota', 'Caballo', 'Reina', 'Rey'];
  const elements = {
    wands: 'fuego — acción y pasión',
    cups: 'agua — emociones y vínculos',
    swords: 'aire — mente y conflicto',
    pentacles: 'tierra — cuerpo y recurso',
  };

  return pips.map((pip, idx) => {
    const isCourt = idx >= 10;
    const rank = isCourt ? ['page', 'knight', 'queen', 'king'][idx - 10] : null;
    const cardName = isCourt ? `${rank === 'page' ? 'Sota' : rank === 'knight' ? 'Caballo' : rank === 'queen' ? 'Reina' : 'Rey'} de ${name}` : `${pip} de ${name}`;

    return {
      id: `${suit}-${idx + 1}`,
      num: idx + 1,
      suit,
      rank,
      name: cardName,
      glyph,
      keywords: cardKeywords(suit, idx + 1),
      upright: cardText(suit, idx + 1, false),
      reversed: cardText(suit, idx + 1, true),
    };
  });
}

/* keywords rápidas por carta-numero-palo */
function cardKeywords(suit, n) {
  const base = {
    wands: {
      1: 'chispa, pasión, nuevo fuego',
      2: 'visión, decisión, expansión',
      3: 'embarque, espera, viaje',
      4: 'hogar, festejo, fundación',
      5: 'conflicto, competencia, fricción',
      6: 'triunfo, victoria, reconocimiento',
      7: 'defender, posición, presión',
      8: 'velocidad, mensajes, movimiento',
      9: 'resiliencia, alerta, prueba',
      10: 'carga, deber, quemar últimas reservas',
      11: 'sota: exploración, entusiasmo',
      12: 'caballo: acción, aventura',
      13: 'reina: magnetismo, calidez',
      14: 'rey: liderazgo, mando',
    },
    cups: {
      1: 'nueva emoción, vaso lleno',
      2: 'unión, romance, conexión',
      3: 'celebración, comunidad, brindis',
      4: 'apatía, oportunidad ignorada',
      5: 'duelo, pérdida parcial',
      6: 'inocencia, nostalgia, infancia',
      7: 'sueños, opciones, confusión',
      8: 'partida, búsqueda, alejarse',
      9: 'satisfacción, deseo cumplido',
      10: 'plenitud emocional, familia',
      11: 'sota: sensibilidad, mensajero',
      12: 'caballo: romanticismo, propuesta',
      13: 'reina: empatía, cuidado',
      14: 'rey: consejero emocional, calma',
    },
    swords: {
      1: 'decisión mental, claridad cortante',
      2: 'equilibrio tenso, decisión postergada',
      3: 'dolor, desgarro, corazón roto',
      4: 'reposo, recuperación, pausa',
      5: 'ganar-pierdes, victoria vacía',
      6: 'transición, dejar el pasado',
      7: 'estrategia, sigilo, maniobras',
      8: 'sentirse atrapado/a, vendas',
      9: 'ansiedad, pesadilla, vigilia',
      10: 'final de ciclo doloroso',
      11: 'sota: curiosidad afilada',
      12: 'caballo: avance brusco',
      13: 'reina: honestidad dura',
      14: 'rey: estrategia, ley',
    },
    pentacles: {
      1: 'oportunidad tangible, ofertar',
      2: 'equilibrio, malabares con recursos',
      3: 'construcción, oficio, equipo',
      4: 'conservar, retener, seguridad',
      5: 'escasez, abandono, pedir',
      6: 'generosidad, dar y recibir',
      7: 'paciencia, inversión, cosecha',
      8: 'oficio, aprendizaje, constancia',
      9: 'lujo, autosuficiencia, premio',
      10: 'fortuna familiar, legado',
      11: 'sota: aprendizaje, primer paso',
      12: 'caballo: camino largo, perseverancia',
      13: 'reina: hogar, fertilidad',
      14: 'rey: magnate, abundancia',
    },
  };
  return base[suit][n].split(',').map(s => s.trim());
}

/* Texto por carta según tema. UPS genera contenido natural sin necesitar IA externa. */
function cardText(suit, n, reversed) {
  const t = {
    wands: {
      1: {
        general: { upr: 'Fuego nuevo prendiendo. Iniciá lo que venís pateando.', rev: 'Chispa que no arranca. Buscá aire, no fuerza.' },
        amor:   { upr: 'Pasión recién encendida. Probable flechazo.', rev: 'Te enojás rápido, te apagás rápido.' },
        dinero: { upr: 'Idea con mucho fuego. Lanzala ya.', rev: 'Impulso sin plan. Bajá un cambio.' },
        salud:  { upr: 'Vitalidad encendida. Cancha.', rev: 'Arranques en falso. Calentá mejor.' },
        prosperidad: { upr: 'Energía emprendedora pura. Aprovéchala.', rev: 'Querer empezar todo y terminar nada.' },
      },
      2: {
        general: { upr: 'Decisión en expansión. Sí a la visión.', rev: 'Duda entre crecer o quedarse.' },
        amor:   { upr: 'Pareja que crece. Decidirse en conjunto.', rev: 'Uno avanza, otro frena.' },
        dinero: { upr: 'Inversión que se expande.', rev: 'Inversión sin definir objetivo.' },
        salud:  { upr: 'Cuerpo con energía creciente.', rev: 'Energía en picos.' },
        prosperidad: { upr: 'Crecimiento real. Sumar.', rev: 'Crecimiento desigual.' },
      },
      3: {
        general: { upr: 'Esperando embarcarte. Mientras tanto: prepará.', rev: 'Retraso que te saca de eje.' },
        amor:   { upr: 'Alguien viene. Esperá el momento.', rev: 'Relación a distancia con mal manejo.' },
        dinero: { upr: 'Proyecto en stand-by. Pronto arranca.', rev: 'Esperar eternidades no es estrategia.' },
        salud:  { upr: 'Buena espera. Mejorá hábitos.', rev: 'Ansiedad por noticias pendientes.' },
        prosperidad: { upr: 'La siembra está brotando.', rev: 'Fruto que no llega.' },
      },
      4: {
        general: { upr: 'Hogar festeja. Reunioná.', rev: 'Tensiones en el nido.' },
        amor:   { upr: 'Aniversario o compromiso hogareño.', rev: 'Convivencia que chispa.' },
        dinero: { upr: 'Estabilidad lograda. Disfrutá.', rev: 'Gastos de familia no previstos.' },
        salud:  { upr: 'Descanso y reparo.', rev: 'Malestar vinculado al hogar.' },
        prosperidad: { upr: 'Abundancia compartida.', rev: 'Falta de frutos en casa.' },
      },
      5: {
        general: { upr: 'Conflicto con pares. Competencia sana o no.', rev: 'Ego en cortocircuito.' },
        amor:   { upr: 'Discusión que aclara o lastima.', rev: 'Fricción que se cronifica.' },
        dinero: { upr: 'Rivalidad comercial. Vos podés.', rev: 'Conflictos legales por plata.' },
        salud:  { upr: 'Inflamación, fiebre, picos.', rev: 'Malestar sostenido.' },
        prosperidad: { upr: 'Pujas. Negociá.', rev: 'Quiebra por litigio.' },
      },
      6: {
        general: { upr: 'Victoria. Reconocimiento te llega.', rev: 'Triunfo empañado por orgullo.' },
        amor:   { upr: 'Pareja gana juntos.', rev: 'Relación basada en aparecer.' },
        dinero: { upr: 'Auge. Subida.', rev: 'Éxito superficial.' },
        salud:  { upr: 'Recuperación total.', rev: 'Mejorar imagen no sano.' },
        prosperidad: { upr: 'Reconocimiento público.', rev: 'Vanidad cara.' },
      },
      7: {
        general: { upr: 'Defendé lo tuyo con firmeza.', rev: 'Ceder terreno por agotamiento.' },
        amor:   { upr: 'Pareja en trincheras. Defendé tu posición.', rev: 'Te rendís por agotamiento emocional.' },
        dinero: { upr: 'Posición financiera defendida.', rev: 'Te están apretando. Cedé lo justo.' },
        salud:  { upr: 'Cuerpo aguanta, pero mucho.', rev: 'Adrenalina sostenida. Frená.' },
        prosperidad: { upr: 'Mantené lo ganado.', rev: 'Desgaste por no soltar.' },
      },
      8: {
        general: { upr: 'Velocidad. Mensaje llega.', rev: 'Apuro que confunde.' },
        amor:   { upr: 'Conversación decisiva o visita.', rev: 'Discusión a las apuradas.' },
        dinero: { upr: 'Noticia financiera buena.', rev: 'Corre sin apuntes.' },
        salud:  { upr: 'Buen pulso. Bajá la velocidad.', rev: 'Agitación. Respirá.' },
        prosperidad: { upr: 'Trato rápido. Aprovéchalo.', rev: 'Apuro que cuesta plata.' },
      },
      9: {
        general: { upr: 'Última guardia. Resistí un poco más.', rev: 'Paranoia en aumento.' },
        amor:   { upr: 'Vínculo en prueba final.', rev: 'Te están por cansar. Alejate.' },
        dinero: { upr: 'Tensión financiera. Aguante.', rev: 'Desgaste por algo que no rinde.' },
        salud:  { upr: 'Cuerpo al límite. Parar ya.', rev: 'Último envión. No más.' },
        prosperidad: { upr: 'Última prueba antes del pico.', rev: 'Insistencia estéril.' },
      },
      10: {
        general: { upr: 'Carga que llevás solo/a. Compartí.', rev: 'Soltar para no caer.' },
        amor:   { upr: 'Relación donde cargás todo.', rev: 'Soltar la mochila.' },
        dinero: { upr: 'Responsabilidad financiera grande.', rev: 'Delegá. No te sauveas solo/a.' },
        salud:  { upr: 'Cansancio sostenido. Pedí ayuda.', rev: 'Burn-out extremo.' },
        prosperidad: { upr: 'Carga empresarial densa.', rev: 'Soltar el bulto.' },
      },
      11: {
        general: { upr: 'Entusiasmo joven. Aprovéchalo.', rev: 'Aplazamientos constantes.' },
        amor:   { upr: 'Coqueteo fresco.', rev: 'No sostienen lo que comienzan.' },
        dinero: { upr: 'Primer ingreso. Inversión inicial.', rev: 'Proyectos truncos.' },
        salud:  { upr: 'Energía joven. Cuidala.', rev: 'Excesos juveniles.' },
        prosperidad: { upr: 'Emprender desde cero.', rev: 'Se cortan solos.' },
      },
      12: {
        general: { upr: 'Aventura directa. Acción.', rev: 'Impulso que lleva a lugar raro.' },
        amor:   { upr: 'Persecución amorosa. Es momento.', rev: 'Demasiado rápido. Frená.' },
        dinero: { upr: 'Buena movida financiera.', rev: 'Aventura con plata que sale mal.' },
        salud:  { upr: 'Cuerpo atlético en plenitud.', rev: 'Accidente deportivo.' },
        prosperidad: { upr: 'Salto emprendededor.', rev: 'Salto al vacío.' },
      },
      13: {
        general: { upr: 'Mujer cálida, magnética. Cerca tuyo.', rev: 'Mujer celosa o insegura.' },
        amor:   { upr: 'Pareja cálida y magnética.', rev: 'Apego disfrazado.' },
        dinero: { upr: 'Mujer que enseña a administrar.', rev: 'Mujer gastadora.' },
        salud:  { upr: 'Mujer vital. Buena influencia.', rev: 'Mujer dependiente oculte.' },
        prosperidad: { upr: 'Mujer que atrae fortuna.', rev: 'Celopatía económica.' },
      },
      14: {
        general: { upr: 'Hombre con mando, voluntad firme.', rev: 'Hombre autoritario o ausente.' },
        amor:   { upr: 'Pareja sólida. Mandato con amor.', rev: 'Mando sin corazón.' },
        dinero: { upr: 'Hombre con dinero. Enseña.', rev: 'Gasta opresivamente.' },
        salud:  { upr: 'Persona con energía.', rev: 'Cansancio autoritario.' },
        prosperidad: { upr: 'Rey. Gran patriarca.', rev: 'Tirano o ausente.' },
      },
    },
    cups: {
      1: {
        general: { upr: 'Emoción nueva, vaso lleno.', rev: 'Vaso seco. Cuidado con la amargura.' },
        amor:   { upr: 'Sentimiento nuevo. Tomá lo que llega.', rev: 'Bloqueo emocional.' },
        dinero: { upr: 'Oportunidad financiera entra.', rev: 'Plata se desperdicia por emocionalidad.' },
        salud:  { upr: 'Bienestar emocional.', rev: 'Sequía emocional, ansiedad.' },
        prosperidad: { upr: 'Ingreso emocional. Reconocimiento.', rev: 'No se recibe lo que se merece.' },
      },
      2: {
        general: { upr: 'Unión perfecta. Vos y otro.', rev: 'Conexión que no termina de cuajar.' },
        amor:   { upr: 'Match. Romance real.', rev: 'Comunicación sin profundidad.' },
        dinero: { upr: 'Socios se alinean.', rev: 'Socios en desacuerdo.' },
        salud:  { upr: 'Pareja terapéutica.', rev: 'Desequilibrio hormonal en pareja.' },
        prosperidad: { upr: 'Blended family fortuna.', rev: 'Familia funciona en dos planos.' },
      },
      3: {
        general: { upr: 'Celebración. Brindis. Alegría.', rev: 'Exceso, juerga que desborda.' },
        amor:   { upr: 'Fiesta amorosa. Con amigos.', rev: 'Chismes.' },
        dinero: { upr: 'Celebración después de logro.', rev: 'Gasto excesivo en festejo.' },
        salud:  { upr: 'Salud que festeja.', rev: 'Resaca.' },
        prosperidad: { upr: 'Comunidad generosa.', rev: 'Red de favores que se corta.' },
      },
      4: {
        general: { upr: 'Apatía. Hay algo mejor y no lo ves.', rev: 'Salís del bajón. Volvés a mirar.' },
        amor:   { upr: 'Alguien llega y no te interesa. Volvé a mirar.', rev: 'Reabrís corazón lentamente.' },
        dinero: { upr: 'Oferta ignorada. Chequeá de nuevo.', rev: 'Efervescencia financiera que vuelve.' },
        salud:  { upr: 'Desgano, hipotiroidismo.', rev: 'Volvés a la rutina sana.' },
        prosperidad: { upr: 'Éxito que no se nota.', rev: 'Salgas del sopor creativo.' },
      },
      5: {
        general: { upr: 'Duelo parcial. Algo se pierde.', rev: 'Recuperás. Ves el vaso medio lleno.' },
        amor:   { upr: 'Pérdida amorosa. Quedan esquirlas.', rev: 'Recuperación sentida.' },
        dinero: { upr: 'Pérdida financiera pequeña.', rev: 'Recuperás lo perdido.' },
        salud:  { upr: 'Enfermedad puntual. Pasa.', rev: 'Mejoría en proceso.' },
        prosperidad: { upr: 'Éxito a medias.', rev: 'Mejora real, no total.' },
      },
      6: {
        general: { upr: 'Nostalgia dulce. Volvés al origen.', rev: 'Estancado en el pasado.' },
        amor:   { upr: 'Amor de la infancia revive. Tierna señal.', rev: 'Apego infantil al amor.' },
        dinero: { upr: 'Ayuda familiar. Donación.', rev: 'Esperando ayuda familiar sin hacer.' },
        salud:  { upr: 'Cuidá lo que viene de antes.', rev: 'Patrón viejo de salud.' },
        prosperidad: { upr: 'Legado que entra.', rev: 'No se cobra la herencia.' },
      },
      7: {
        general: { upr: 'Muchos caminos. Soñás despierto/a.', rev: 'Decisión clara llega.' },
        amor:   { upr: 'Amantes posibles. Elegí.', rev: 'Salir de la indefinición.' },
        dinero: { upr: 'Muchas ofertas. Una sola es la buena.', rev: 'Foco al fin.' },
        salud:  { upr: 'Opciones de tratamiento. Compará.', rev: 'Una terapia concreta.' },
        prosperidad: { upr: 'Sueños materiales varios.', rev: 'Realismo vuelve.' },
      },
      8: {
        general: { upr: 'Volver a caminar. Buscás algo más.', rev: 'Quedarte o volver. Decidí.' },
        amor:   { upr: 'Pareja se aleja. No la persigas.', rev: 'Se acerca alguien. Esperá.' },
        dinero: { upr: 'Trabajo que no llena. Salir.', rev: 'Volvés por convicción.' },
        salud:  { upr: 'Sanar caminando.', rev: 'Buscar mejor sanación.' },
        prosperidad: { upr: 'Salir de lo que no crece.', rev: 'Volver a lo conocido.' },
      },
      9: {
        general: { upr: 'Deseo cumplido. Saudade satisfecha.', rev: 'Deseo no cumplido todavía.' },
        amor:   { upr: 'Amor soñado llega.', rev: 'Falta de fe en el amor.' },
        dinero: { upr: 'Compra que querías llega.', rev: 'Plata esperada no llega.' },
        salud:  { upr: 'Bienestar pleno.', rev: 'Algo no responde.' },
        prosperidad: { upr: 'Reconocimiento público masivo.', rev: 'Casi. Casi.' },
      },
      10: {
        general: { upr: 'Familia plena. Hogar completo.', rev: 'Disfunción familiar conocida.', rev2: 'Algo se desarma en casa.' },
        amor:   { upr: 'Familia que celebra el amor.', rev: 'Pareja disfuncional de origen.' },
        dinero: { upr: 'Familia como red de fortuna.', rev: 'Heredás problemas financieros.' },
        salud:  { upr: 'Cuerpo familiar. Fertilidad.', rev: 'Patrón hereditario a desarmar.' },
        prosperidad: { upr: 'Fortuna familiar consolidada.', rev: 'Fortuna en disputa.' },
      },
      11: {
        general: { upr: 'Mensaje emocional. Alguien te dice lo que siente.', rev: 'Mensaje confuso.' },
        amor:   { upr: 'Coqueteo, propuesta.', rev: 'Malentendido romántico.' },
        dinero: { upr: 'Alguien te trae una posibilidad.', rev: 'Mensaje confuso sobre plata.' },
        salud:  { upr: 'Mensaje del cuerpo: cuidá el agua.', rev: 'Atender el cuerpo sensible.' },
        prosperidad: { upr: 'Reconocimiento llega con carta.', rev: 'Mensaje que demora.' },
      },
      12: {
        general: { upr: 'Propuesta emocional, avanzar.', rev: 'Prometés y no cumplís.' },
        amor:   { upr: 'Caballero andante. Se acerca.', rev: 'Inconstancia.' },
        dinero: { upr: 'Oferta que llega a caballo. Rápida.', rev: 'Demasiado rápido. Frená.' },
        salud:  { upr: 'Cuerpo en movimiento.', rev: 'Lesión deportiva.' },
        prosperidad: { upr: 'Viaje que abre.', rev: 'Viaje perdido.' },
      },
      13: {
        general: { upr: 'Mujer empática, sensible, sabia.', rev: 'Mujer insegura o voluble.' },
        amor:   { upr: 'Mujer que cuida y comprende.', rev: 'Mujer celosa.' },
        dinero: { upr: 'Mujer con intuición financiera.', rev: 'Mujer voluble con plata.' },
        salud:  { upr: 'Mujer sana, sensible a la sanación.', rev: 'Mujer que se boicotea.' },
        prosperidad: { upr: 'Mujer que magnetiza fortuna.', rev: 'Emociones sabotean prosperidad.' },
      },
      14: {
        general: { upr: 'Hombre emocional estable.', rev: 'Hombre voluble.' },
        amor:   { upr: 'Hombre que cuida sin asfixiar.', rev: 'Hombre impredecible.' },
        dinero: { upr: 'Hombre con don de gente financiero.', rev: 'Hombre que oscila entre abundancia y escasez.' },
        salud:  { upr: 'Hombre emocionalmente sano.', rev: 'Hombre con ansiedad crónica.' },
        prosperidad: { upr: 'Rey emocional. Cimientos firmes.', rev: 'Muros blandos.' },
      },
    },
    swords: {
      1: {
        general: { upr: 'Decisión de claridad quirúrgica.', rev: 'Confusión reinante. Parar.' },
        amor:   { upr: 'Decisión sobre alguien. Ahora.', rev: 'No podés decidir.' },
        dinero: { upr: 'Corte limpio. Cerrar o abrir.', rev: 'Decisión que se posterga.' },
        salud:  { upr: 'Diagnóstico certero.', rev: 'Segundo opinión.' },
        prosperidad: { upr: 'Acción mental coordinada.', rev: 'Ideas no aterrizan.' },
      },
      2: {
        general: { upr: 'Equilibrio tenso. Dos opciones.', rev: 'Una se cae. Decidí.' },
        amor:   { upr: 'Pareja en duda. Hablar.', rev: 'Decisión a tomar ya.' },
        dinero: { upr: 'Balance delicadísimo.', rev: 'Perdés equilibrio financiero.' },
        salud:  { upr: 'Vértigo momentáneo.', rev: 'Decisión de tratamiento.' },
        prosperidad: { upr: 'Decisión pendiente.', rev: 'Definir por cuál vas.' },
      },
      3: {
        general: { upr: 'Herida abierta. Duele, sí.', rev: 'Curás la herida. Lentamente.' },
        amor:   { upr: 'Corazón roto. Tiempo.', rev: 'Vas sanando.' },
        dinero: { upr: 'Pérdida financiera fuerte.', rev: 'Recuperación financiera. Lenta.' },
        salud:  { upr: 'Dolor físico puntual.', rev: 'Mejoría lenta pero real.' },
        prosperidad: { upr: 'Crack previsto. Pasa.', rev: 'Saneás pérdidas pasadas.' },
      },
      4: {
        general: { upr: 'Reposo merecido. Descansá.', rev: 'Volvés a la acción. Lento.' },
        amor:   { upr: 'Pareja en pausa.', rev: 'Reactivás el vínculo.' },
        dinero: { upr: 'Cuatro plazas financieras. Esperá.', rev: 'Reactivás economía con cuidado.' },
        salud:  { upr: 'Reposo corporal absoluto.', rev: 'Rehabilitación.' },
        prosperidad: { upr: 'Cuatro días de no hacer. Sirve.', rev: 'Salir del reposo.' },
      },
      5: {
        general: { upr: 'Ganar a costa de perder. Caro.', rev: 'Volvés a dialogar.' },
        amor:   { upr: 'Triunfo que cuesta la relación.', rev: 'Reparar lo roto.' },
        dinero: { upr: 'Ganaste, pero debés.', rev: 'Aprendés a ganar limpio.' },
        salud:  { upr: 'Enfermedad que pudo evitarse.', rev: 'Diagnóstico que se rectifica.' },
        prosperidad: { upr: 'Victoria pírrica.', rev: 'Reparación material.' },
      },
      6: {
        general: { upr: 'Transición. Dejar el pasado.', rev: 'No querés soltar. Volvé a mirar.' },
        amor:   { upr: 'Dejar atrás para avanzar.', rev: 'Aún cargás con alguien.' },
        dinero: { upr: 'Migración financiera. Adelante.', rev: 'Patrón económico viejo se repite.' },
        salud:  { upr: 'Mejorar hábitos viejos.', rev: 'Volver al patrón conocido cuesta.' },
        prosperidad: { upr: 'Éxodo sano.', rev: 'Volver con retorno.' },
      },
      7: {
        general: { upr: 'Astucia. Estrategia silenciosa.', rev: 'Caer en el engaño ajeno.' },
        amor:   { upr: 'Estrategia en pareja.', rev: 'Alguien te está jugando.' },
        dinero: { upr: 'Negociación furtiva. Cuidadosa.', rev: 'Operación financiera que se cae.' },
        salud:  { upr: 'Sutil mejora por dentro.', rev: 'Enfermedad oculta. Chequeo.' },
        prosperidad: { upr: 'Operación silenciosa rentable.', rev: 'Plata que se va sin dejar huella.' },
      },
      8: {
        general: { upr: 'Te sentís atrapado/a. Las vendas.', rev: 'Te desatás.' },
        amor:   { upr: 'Relación que limita.', rev: 'Soltás ataduras.' },
        dinero: { upr: 'Bolsillo apretado sin salida clara.', rev: 'Recuperás el control financiero.' },
        salud:  { upr: 'Adicciones que limitan.', rev: 'Soltás la sustancia.' },
        prosperidad: { upr: 'Atrapado en el sistema.', rev: 'Rompes el ciclo.' },
      },
      9: {
        general: { upr: 'Ansiedad, pesadillas, vigilia.', rev: 'Mejor descansar. Ya vas a calmarte.' },
        amor:   { upr: 'Miedos nocturnos en pareja.', rev: 'Tranquilizás un poco.' },
        dinero: { upr: 'Preocupaciones que no dejan dormir.', rev: 'Mejora la noche. Y el día.' },
        salud:  { upr: 'Estrés mental fuerte.', rev: 'Te calmás. Tratamiento.' },
        prosperidad: { upr: 'Miedo al futuro.', rev: 'Empezás a confiar.' },
      },
      10: {
        general: { upr: 'Final de ciclo duro. Mirá el amanecer.', rev: 'Esto no se acabó del todo.' },
        amor:   { upr: 'Fin de relación. Duelo que termina.', rev: 'Recaída emocional. Atención.' },
        dinero: { upr: 'Quiebre material que ya pasó.', rev: 'Final aún no termina.' },
        salud:  { upr: 'Diagnóstico fuerte. Mejora.', rev: 'Enfermedad vuelve. Cuidá.' },
        prosperidad: { upr: 'Tocar fondo. Rebotás.', rev: 'Fondo aún más hondo.' },
      },
      11: {
        general: { upr: 'Mente afilada. Curiosidad.', rev: 'Chusma que distrae.' },
        amor:   { upr: 'Chispa mental con alguien.', rev: 'Coqueteo que es solo ruido.' },
        dinero: { upr: 'Habilidad para Plata.', rev: 'Espionaje en lugar de trabajo.' },
        salud:  { upr: 'Mente activa. Bueno.', rev: 'Rumiación.' },
        prosperidad: { upr: 'Curiosidad que te hace ganar.', rev: 'Espiar más que crear.' },
      },
      12: {
        general: { upr: 'Avance rápido. Cabalgata mental.', rev: 'Apuro que atropella.' },
        amor:   { upr: 'Relación avanza rápido.', rev: 'Velocidad que asusta.' },
        dinero: { upr: 'Inversión veloz que rinde.', rev: 'Apuro que vuelca.' },
        salud:  { upr: 'Cuerpo rápido.', rev: 'Accidente por ir rápido.' },
        prosperidad: { upr: 'Estrategia ejecutiva.', rev: 'Apuro que descarrila.' },
      },
      13: {
        general: { upr: 'Mujer directa, inteligente.', rev: 'Mujer dura que no se deja.' },
        amor:   { upr: 'Mujer independiente. Admirable.', rev: 'Mujer distante o cínica.' },
        dinero: { upr: 'Mujer con cabeza financiera.', rev: 'Mujer desconfiada con Plata.' },
        salud:  { upr: 'Mujer lúcida. Cuidá la mente.', rev: 'Rigidez mental.' },
        prosperidad: { upr: 'Gran Reina intelectual.', rev: 'Dureza que aísla.' },
      },
      14: {
        general: { upr: 'Hombre de ley, lógica, poder.', rev: 'Hombre tirano o frío.' },
        amor:   { upr: 'Hombre que estructura con amor.', rev: 'Hombre sin ternura.' },
        dinero: { upr: 'Hombre de poder financiero.', rev: 'Hombre cortante con Plata.' },
        salud:  { upr: 'Hombre recto. Salud fuerte.', rev: 'Hombre que se descontrola.' },
        prosperidad: { upr: 'Rey de Espadas. Cúspide mental.', rev: 'Rey aislado.' },
      },
    },
    pentacles: {
      1: {
        general: { upr: 'Oportunidad tangible. Ofrenda. Tomala.', rev: 'Oportunidad se cae por no planear.' },
        amor:   { upr: 'Alguien concreto se acerca.', rev: 'Pretendiente con plata no llega.' },
        dinero: { upr: 'Ingreso grande concreto.', rev: 'Ingreso se diluye.' },
        salud:  { upr: 'Cuerpo recibiendo energía nueva.', rev: 'Mala alimentación.' },
        prosperidad: { upr: 'Maná. Aprovechá.', rev: 'Desperdicio.' },
      },
      2: {
        general: { upr: 'Malabares. Equilibrio fino.', rev: 'Perdés un plato.' },
        amor:   { upr: 'Pareja con tiempos divididos.', rev: 'No podés con todo.' },
        dinero: { upr: 'Dos entradas. Administrá.', rev: 'Doble gasto.' },
        salud:  { upr: 'Dieta balanceada.', rev: 'Cuerpo pide equilibrio.' },
        prosperidad: { upr: 'Dos proyectos a la vez.', rev: 'Caen los dos.' },
      },
      3: {
        general: { upr: 'Construcción con equipo. Oficio.', rev: 'Equipo falla. Volvé a planificar.' },
        amor:   { upr: 'Construir pareja con cimientos.', rev: 'Falta comunicación práctica.' },
        dinero: { upr: 'Proyecto a punto de salir.', rev: 'Proyecto trunco por desacuerdo.' },
        salud:  { upr: 'Tratamiento avanzando.', rev: 'Terapia discontinua.' },
        prosperidad: { upr: 'Edificar fortuna. Adelante.', rev: 'Construcción sin arquitecto.' },
      },
      4: {
        general: { upr: 'Aferrarse al recurso. Tenedor firme.', rev: 'Soltá un poco. Compartir.' },
        amor:   { upr: 'Pareja que ahorra pero no disfruta.', rev: 'Abrirse con el otro/a.' },
        dinero: { upr: 'Ahorro fuerte.', rev: 'Exceso de ahorro que enferma.' },
        salud:  { upr: 'Salud estable.', rev: 'Restricción extrema.' },
        prosperidad: { upr: 'Bóveda fuerte.', rev: 'Abrir la bóveda.' },
      },
      5: {
        general: { upr: 'Escarces. Pedir. Pedir ayuda.', rev: 'Recuperás algo. Lentamente.' },
        amor:   { upr: 'Pareja en falta. Pedir.', rev: 'Recuperás lo perdido.' },
        dinero: { upr: 'Apuros fuertes.', rev: 'Vuelve lo justo.' },
        salud:  { upr: 'Falta de vitaminas.', rev: 'Mejora la nutrición.' },
        prosperidad: { upr: 'Quiebre parcial.', rev: 'Salir con esfuerzo.' },
      },
      6: {
        general: { upr: 'Generosidad. Dar y recibir.', rev: 'Dás sin que te devuelvan.' },
        amor:   { upr: 'Generosidad en pareja. Equilibrada.', rev: 'Dás de más.' },
        dinero: { upr: 'Prestar/a con cuidado.', rev: 'Prestamos impagos.' },
        salud:  { upr: 'Dar al cuerpo lo necesario.', rev: 'Exceso de bienes, poco movimiento.' },
        prosperidad: { upr: 'Red generosa.', rev: 'Explotado/a.' },
      },
      7: {
        general: { upr: 'Paciencia. Cosecha en su tiempo.', rev: 'Cosecha no llega por dudar.' },
        amor:   { upr: 'Inversión emocional con tiempo.', rev: 'Inversión que no rindió.' },
        dinero: { upr: 'Esperar rendimiento.', rev: 'Sacar antes de tiempo.' },
        salud:  { upr: 'Tratamiento con paciencia.', rev: 'Inconstancia en el cuidado.' },
        prosperidad: { upr: 'Esperar dividendo.', rev: 'Fruto que no salió.' },
      },
      8: {
        general: { upr: 'Aprender y practicar. Oficio.', rev: 'Oficio abandonado por orgullo.' },
        amor:   { upr: 'Relación que enseña paciencia.', rev: 'Volvés a buscar pareja sin crecer.' },
        dinero: { upr: 'Aprender a ganar con habilidad.', rev: 'Creer saber sin practicar.' },
        salud:  { upr: 'Cuerpo aprendiendo a cuidarse.', rev: 'Sabotaje al tratamiento.' },
        prosperidad: { upr: 'Te labrás con esfuerzo.', rev: 'Esperás atajo.' },
      },
      9: {
        general: { upr: 'Lujo merecido. Disfrute digno.', rev: 'Falsificar la abundancia.' },
        amor:   { upr: 'Pareja con sus bienes.', rev: 'Apariencia.' },
        dinero: { upr: 'Independencia financiera.', rev: 'Apariencia de riqueza.' },
        salud:  { upr: 'Vigor excelente.', rev: 'Cuidado que es fachada.' },
        prosperidad: { upr: 'Lujo prudente.', rev: 'Apariencia falsa.' },
      },
      10: {
        general: { upr: 'Familia multigeneracional en fortuna.', rev: 'Familia en pelea por dinero.' },
        amor:   { upr: 'Familia armónica alrededor.', rev: 'Disputa familiar.' },
        dinero: { upr: 'Legado. Herencia.', rev: 'Herencia mal repartida.' },
        salud:  { upr: 'Familia sana. Genes buenos.', rev: 'Patrón genético a romper.' },
        prosperidad: { upr: 'Fortuna familiar. Cúspide.', rev: 'Fortuna en disputa.' },
      },
      11: {
        general: { upr: 'Primer paso. Estudio. Ilusión.', rev: 'Empezar y dejar.' },
        amor:   { upr: 'Coqueteo inicial.', rev: 'No avanza.' },
        dinero: { upr: 'Primer ahorro.', rev: 'Plata chica sin inversión.' },
        salud:  { upr: 'Primer paso al bienestar.', rev: 'Abandonás la dieta.' },
        prosperidad: { upr: 'Estudio rentable.', rev: 'Estudio trunco.' },
      },
      12: {
        general: { upr: 'Perseverancia paciente. Avance seguro.', rev: 'Estancamiento por fatiga.' },
        amor:   { upr: 'Relación larga. Constancia.', rev: 'Cansado/a de intentar.' },
        dinero: { upr: 'Inversión a largo plazo.', rev: 'Fatiga financiera.' },
        salud:  { upr: 'Ejercicio constante.', rev: 'Lesión por uso.' },
        prosperidad: { upr: 'Largo camino. Adelante.', rev: 'Rendirse.' },
      },
      13: {
        general: { upr: 'Mujer práctica, fecunda, hogareña.', rev: 'Mujer que descuida el nido.' },
        amor:   { upr: 'Mujer cálida y concreta.', rev: 'Mujer absorbente.' },
        dinero: { upr: 'Mujer con abundancia.', rev: 'Mujer gastadora.' },
        salud:  { upr: 'Cuerpo sano. Fertilidad.', rev: 'Hormonal alterado.' },
        prosperidad: { upr: 'Reina de la abundancia.', rev: 'Reina que descuida sus frutos.' },
      },
      14: {
        general: { upr: 'Hombre con plata y oficio.', rev: 'Hombre con dinero pero mezquino.' },
        amor:   { upr: 'Hombre que ofrece seguridad.', rev: 'Hombre que controla con dinero.' },
        dinero: { upr: 'Hombre magnate. Sabio.', rev: 'Hombre que se pierde en lo material.' },
        salud:  { upr: 'Hombre sano y estable.', rev: 'Hombre come mal, estrés.' },
        prosperidad: { upr: 'Rey de Oros. Cúspide.', rev: 'Rey que se está secando.' },
      },
    },
  };

  const data = t[suit][n];
  const out = {
    general: data.general.upr,
    amor: data.amor.upr,
    dinero: data.dinero.upr,
    salud: data.salud.upr,
    prosperidad: data.prosperidad.upr,
  };
  const outR = {
    general: data.general.rev,
    amor: data.amor.rev,
    dinero: data.dinero.rev,
    salud: data.salud.rev,
    prosperidad: data.prosperidad.rev,
  };
  return reversed ? outR : out;
}

if (typeof module !== 'undefined') module.exports = { DECK };
